# mode
mode = "default"

# log 
log_level = "info"  # trace|debug|info|warn|error
log_path = "./logs"

# database setting
database_uri = "mongodb://localhost:27017"
database_name = "cgm-default"

# bind address
bind_addr = "0.0.0.0:8899"